### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/Toxin#1]
Не собирается - не может найти montserrat-bold.ttf. Надо исправить и проверить, что всё работает после клонирования и запуска.

**Comment by performanceArtist** [comment]
docs надо тоже в gitignore добавить, т.к. их изменение - это лишний шум в коммитах.

**Comment by skinnynpale** [comment]
Я просил передать чтобы начали с rangeslider

**Comment by skinnynpale** [comment]
Начнете с него ладно? Тут нужно еще кое что допилить, просто чтобы вы меньше времени потратили

**Comment by performanceArtist** [comment]
Ладно.

**Comment by skinnynpale** [comment]
> Ещё docs надо тоже в gitignore добавить, т.к. их изменение - это лишний шум в коммитах.

docs используется только когда обновляю github pages, а это отдельный коммит. Все промежуточные хранятся в dist а она под игнором

**Comment by skinnynpale** [comment]
> Не собирается - не может найти montserrat-bold.ttf. Надо исправить и проверить, что всё работает после клонирования и запуска.

Протестил, у меня все работает. Не покажешь где ошибка возникает?

**Comment by skinnynpale** [comment]
Кстати, можешь врываться, я закончил правки

**Comment by performanceArtist** [comment]
У тебя регистр не тот в импортах. К такому windows не чувствителен, но на unix-подобных как раз это ошибка.

**Comment by skinnynpale** [comment]
Готово

7f1e1b2cba065f66f25441a14ed876b5572f08a1
20cea614ed123222788bf52d5014b53f818e9bae
cb0665c4a6bf807eb921385a5930476f0b87cfad
