### ISSUE TITLE
id

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/Toxin#11]
Использование id затрудняет переиспользование - на странице могут быть конфликты, а в css селектор по id имеет большую специфичность. В инпутах для привязки label использовать можно, но почему у тебя у самого label тот же id в toggle? #rangeSliderRoomValue - компонент сам должен знать, как найти элемент. У него должна быть эта логика, а не так что мне каждый раз нужно брать этот кусок кода и руками его куда-то вставлять. Все эти id(moreComfortFilter, moreComfortFilterWrapper и т.д.) - какие-то костыли. Эти внутренности должны быть инкапсулированы в классе, снаружи о них знать никто не должен.

**Comment by skinnynpale** [comment]
fixed moreComfortFIlter - c18a2788fbd4617dd410b21006544454602ee4e7
