### ISSUE TITLE
Параметры миксинов

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/Toxin#5]
`mixin field-group(classes, text1, id1, text2, id2, value1, value2)`

Для передачи нескольких параметров лучше использовать объект и деструктуризацию. Тогда не нужно будет запоминать порядок аргументов + можно там же задать значения по умолчанию.

**Comment by performanceArtist** [comment]
Имена тоже надо привести в порядок, цифр в них быть не должно.

**Comment by skinnynpale** [comment]
Готово
