### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by performanceArtist** [skinnynpale/Toxin#6]
Не должно быть элементов без блока, как в advantages.

**Comment by performanceArtist** [comment]
`.dropdown__btn_disable`

Напрямую на стили блока другой блок влиять не должен. Стили должны меняться через модификаторы блока. Позиционирование задаётся через элемент-обёртку.

**Comment by performanceArtist** [comment]
`form.check-form.datepicker-place`

Мешать классы тоже недопустимо.

**Comment by skinnynpale** [comment]
> 
> 
> `.dropdown__btn_disable`
> 
> Напрямую на стили блока другой блок влиять не должен. Стили должны меняться через модификаторы блока. Позиционирование задаётся через элемент-обёртку.

Это родной блок

**Comment by performanceArtist** [comment]
`.js-dropdown__content` - почему для него какие-то особые стили есть? По идее стили должны быть в .dropdown__content, .js-dropdown__content уже используется для выборки с js.

**Comment by performanceArtist** [comment]
```
.header-footer
  background-color: #F4F4F6
  > div
    margin-bottom: 1.4286rem
```
Подобные вещи лучше чётко разграничить - селекторы делать по элементам, чтобы сразу по css было понятно, что стилизуется.

**Comment by performanceArtist** [comment]
```
.header-non-authorized
            .section__item
```

Здесь элемент в воздухе повис без блока.

**Comment by performanceArtist** [comment]
В form-elements куча селекторов по div и прочим тегам. Элементы тоже есть без блоков. Посмотри везде.

**Comment by performanceArtist** [comment]
Это ещё к слову о компонентности - селекторы в рамках страницы(блока) не должны быть рабросаны как попало. Всё внутри должно быть элементами блока - не надо мешать кучу левых классов.

**Comment by performanceArtist** [comment]
В cards селектор не тот: .ui-kit__section. Это должен быть блок, а не элемент в своей папке.

**Comment by performanceArtist** [comment]
```
.d100
  background-color: $accent
```

Вместо миксов сделать модификаторы.

**Comment by performanceArtist** [comment]
В user-form кроме css ничего нет, а pug-код в другой папке.

**Comment by performanceArtist** [comment]
span(class= "rate__wrapper")

Тоже элемент без блока.

**Comment by performanceArtist** [comment]
button.btn.like__btn

Тоже миксы.

**Comment by performanceArtist** [comment]
```
.container
  @include container
  display: flex
  justify-content: space-between
  padding: 0 1.0714rem

  .main__item
    max-width: 50rem

.label
  @include label
```
Вот эти правила есть в ui-kit.sass, но блоков я таких нигде не вижу. Если есть переиспользуемый функционал, надо его явно выделять. Ты представь, какого тебе менять будет подобное, если там где-то в глубине страниц десятки таких классов навешано.

**Comment by performanceArtist** [comment]
```
.form-elements_expandable
  .fields
    width: 19rem

.advantages
  padding: 0
```

Тут тоже миксы, нарушение инкапсуляции. Вообще тот случай, если у тебя в css блока упоминаются другие блоки, уже указывает на нарушение компонентного подхода.

**Comment by performanceArtist** [comment]
```
.type
      .type__item.type__item--h1
```
Тут тоже надо явно выделить, а не харкодить. Я же говорил вроде, что просто кусков вёрстки быть не должно, тем более в пределах другого блока.

**Comment by performanceArtist** [comment]
В rooms тоже много всего, надо как-то разбить или сделать что-то частью блока.

**Comment by performanceArtist** [comment]
ui-kit всё равно просачивается в другие компоненты. В colors и types значения захардкожены.

**Comment by performanceArtist** [comment]
В вёрстке cards два класса левых - .ui-kit, .rooms__item. Почему бы сразу везде не посмотреть и не исправить?

**Comment by performanceArtist** [comment]
В sign-up какой-то класс main - имена блока, папки и файлов должны совпадать.

**Comment by performanceArtist** [comment]
```figure.gallery__item.gallery__item--1```

Тут во-первых блок надо вынести, во вторых идут имена с цифрами, притом используется только селектор для первого.

**Comment by performanceArtist** [comment]
Странный файл получается: называется page-room, содержит три блока, притом блок, по которому назван файл, даже в стилях не присутствует.

**Comment by performanceArtist** [comment]
В rooms-page название блока не то - оно должно с именем файла совпадать.

**Comment by performanceArtist** [comment]
```
.cards__item
                .rooms__item
```

Левый элемент без блока.
